### ISSUE TITLE
Alternative (-:)/2 for (=>)/2

### ISSUE THREAD

**Issue by jburse** [josd/seeye#1]
So there is time to do something differently? I tried to avoid the (=>)/2 problem by using (-:)/2 instead. Its just the mirror of (:-)/2. I picked seeye.pl and graph.pl. Whats the license, is it possibly to modify your code and upload it on gist as I did below?

Here are benchmark results, my system and SWI-Prolog:
```
?- time((between(1,10000,_), retractall(path(_,_)), 
             retractall(goal), seeye, fail; true)).
% Up 745 ms, GC 5 ms, Threads 738 ms (Current 02/14/21 01:28:55)
Yes

?- time((between(1,10000,_), retractall(path(_,_)), 
             retractall(goal), seeye, fail; true)).
% 3,370,000 inferences, 0.775 CPU in 0.865 seconds (90% CPU, 4349218 Lips)
true.
```
How do you like the operator (-:)/2 ? With this operator (-:)/2 you could have backward chaining rules realized through SWI-Prolog Picat style match (=>)/2 used by “Second eye”!

Open source:

**Seeye performs controlled chaining**
[https://gist.github.com/jburse/6fb59e01e3e1017303afc513d93caaa1#file-seeye-pl
](https://gist.github.com/jburse/6fb59e01e3e1017303afc513d93caaa1#file-seeye-pl
)
**Traversing graph paths**
[https://gist.github.com/jburse/6fb59e01e3e1017303afc513d93caaa1#file-graph-pl](https://gist.github.com/jburse/6fb59e01e3e1017303afc513d93caaa1#file-graph-pl)

**Comment by josd** [comment]
I was actually introducing (-:)/2 in https://github.com/infradig/trealla/issues/132 to give the reasoner a hint to do forward chaining (instead of the usual backward chaining for (:-)/2) because I couldn’t find another way to solve the dpe.pl test case (trying hard with tabling but was loosing). But then coming from a Notation3 world where you simply say PREM => CONC as well as in the coherent logic and the TPTP world, logical implication is represented by the operator (=>)/2. I found the new use in swipl HEAD => BODY really contradictory with the classical logic use BODY => HEAD i.e. PREM => CONC.

**Comment by josd** [comment]
See also https://github.com/josd/seeye/blob/master/LICENSE

**Comment by josd** [comment]
So will decide in the coming weeks to eventually revert to (-:)/2 :-)

**Comment by josd** [comment]
Fair enough, am reverting to original `(-:)/2` notation
https://github.com/josd/seeye/commit/31dd8d5fae7d19ad5d042ad1dc107a39f93ae2de
